version: "3.9"
services:
  api:
    build:
      context: .
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    ports:
      - "5432:5432"
